# Generated by Django 2.2.4 on 2019-10-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': "Comments's"},
        ),
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(null=True, to='mediaportal_app.Comments'),
        ),
    ]
