# Generated by Django 2.2.4 on 2019-10-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportal_app', '0004_article_time_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(blank=True, to='mediaportal_app.Comments'),
        ),
    ]
