# Generated by Django 2.2.4 on 2019-10-14 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediaportal_app', '0005_auto_20191012_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='users_reactions',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
