# Generated by Django 2.2.4 on 2019-10-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaportal_app', '0007_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='favourite_articles',
            field=models.ManyToManyField(blank=True, to='mediaportal_app.Article'),
        ),
    ]
